### ISSUE TITLE
Unknown Exception: option parser

### ISSUE THREAD

**Issue by KINGSABRI** [KINGSABRI/jwtear#2]
```
jwtear --generate-sig 
[x] Unknown Exception: option parser
[!] Please report the issue at: https://github.com/KINGSABRI/jwtear/issues
/usr/lib/ruby/2.4.0/base64.rb:66:in `pack'
/usr/lib/ruby/2.4.0/base64.rb:66:in `strict_encode64'
/usr/lib/ruby/2.4.0/base64.rb:84:in `urlsafe_encode64'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:5:in `encode'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `block in encode_header_payload'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `map'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `encode_header_payload'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/bin/jwtear:97:in `<top (required)>'
/usr/local/bin/jwtear:23:in `load'
/usr/local/bin/jwtear:23:in `<main>'
/usr/lib/ruby/2.4.0/base64.rb:66:in `pack'
/usr/lib/ruby/2.4.0/base64.rb:66:in `strict_encode64'
/usr/lib/ruby/2.4.0/base64.rb:84:in `urlsafe_encode64'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:5:in `encode'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `block in encode_header_payload'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `map'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/lib/jwtear/utils.rb:13:in `encode_header_payload'
/var/lib/gems/2.4.0/gems/jwtear-0.1.0/bin/jwtear:97:in `<top (required)>'
/usr/local/bin/jwtear:23:in `load'
/usr/local/bin/jwtear:23:in `<main>'
no implicit conversion of nil into String
```

**Comment by KINGSABRI** [comment]
fixed in 44e9af23a42e4b576f989c4b094f7973f39e1eb7
